#ifndef _MAP_DATA_CONST_VARIABLES_H_
#define _MAP_DATA_CONST_VARIABLES_H_

/*
 * Warning this file was generated by the Level Editor
*/

namespace MapManager
{
	// size of the level
	static constexpr int LEVEL_WIDTH = 48;
	static constexpr int LEVEL_HEIGHT = 32;

	// number of puzzle screen
	static constexpr int PUZZLE_SCREEN_COUNT = 4;
	static constexpr int PUZZLE_SCREEN_BYTE_COUNT = 1;

	// coordinates of the first puzzle screen and main menu
	static constexpr int MAIN_MENU_CAMERA_X = 0;
	static constexpr int MAIN_MENU_CAMERA_Y = 0;
	static constexpr int FIRST_PUZZLE_SCREEN_CAMERA_X = 16;
	static constexpr int FIRST_PUZZLE_SCREEN_CAMERA_Y = 24;
};

#endif
